'''
CSE 415 Final Project
Yinghe Chen, Yu Fu
June 2, 2015
licensePlateImgToText.py

This is the main program of the license plate recognization.
It reads images generated by plateSegmentation.py.
The program uses bagging method to combine two kinds of classifiers:
Naive Bayes Classifier and Perceptron Classifier
Make 4 Naive Bayes classifiers and 5 Perceptron Classifier
that trained from different subsets of training set,
and uses the most voted characters as the final result.
'''

import naiveBayesClassifier as nb1
import naiveBayesClassifier as nb2
import naiveBayesClassifier as nb3
import naiveBayesClassifier as nb4
import perceptronClassifier as pc1
import perceptronClassifier as pc2
import perceptronClassifier as pc3
import perceptronClassifier as pc4
import perceptronClassifier as pc5

def most_common(lst):
    '''Return the most common item in the given list.'''
    return max(set(lst), key=lst.count)

def get_text(img_dir):
    '''Generate the license plate number from images in the given directory.'''
    result0 = nb1.imgToString(img_dir)
    result1 = nb2.imgToString(img_dir)
    result2 = nb3.imgToString(img_dir)
    result3 = nb4.imgToString(img_dir)
    result4 = pc1.imgToString(img_dir)
    result5 = pc2.imgToString(img_dir)
    result6 = pc3.imgToString(img_dir)
    result7 = pc4.imgToString(img_dir)
    result8 = pc5.imgToString(img_dir)
    results = [result0, result1, result2, result3, result4, result5, result6, result7, result8]

    for i in range(len(results)):
        print("Classifier " + str(i+1) + ": " + results[i].upper())

    chars = []
    for i in range(len(results[0])):
        char_i = []
        for result in results:
            char_i.append(result[i])
        chars.append(char_i)

    output = ''
    for char in chars:
        output += most_common(char)
    print("The final result is " + output.upper())

get_text('Images/seg_test/test_2')

